src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Street = null;

    #[ORM\Column(length: 255)]
    private ?string $City = null;

    #[ORM\Column]
    private ?int $Zip = null;

    #[ORM\ManyToOne(inversedBy: 'Address')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\OneToMany(mappedBy: 'Address', targetEntity: Acquisition::class)]
    private Collection $Acquisition;

    public function __construct()
    {
        $this->Acquisition = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->Street;
    }

    public function setStreet(string $Street): self
    {
        $this->Street = $Street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getZip(): ?int
    {
        return $this->Zip;
    }

    public function setZip(int $Zip): self
    {
        $this->Zip = $Zip;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Acquisition>
     */
    public function getAcquisition(): Collection
    {
        return $this->Acquisition;
    }

    public function addAcquisition(Acquisition $acquisition): self
    {
        if (!$this->Acquisition->contains($acquisition)) {
            $this->Acquisition->add($acquisition);
            $acquisition->setAddress($this);
        }

        return $this;
    }

    public function removeAcquisition(Acquisition $acquisition): self
    {
        if ($this->Acquisition->removeElement($acquisition)) {
            // set the owning side to null (unless already changed)
            if ($acquisition->getAddress() === $this) {
                $acquisition->setAddress(null);
            }
        }

        return $this;
    }
}

src/Entity/Bank.php
<?php

namespace App\Entity;

use App\Repository\BankRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BankRepository::class)]
class Bank
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $Amount = null;

    #[ORM\OneToOne(mappedBy: 'Bank', cascade: ['persist', 'remove'])]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(?int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        // unset the owning side of the relation if necessary
        if ($User === null && $this->User !== null) {
            $this->User->setBank(null);
        }

        // set the owning side of the relation if necessary
        if ($User !== null && $User->getBank() !== $this) {
            $User->setBank($this);
        }

        $this->User = $User;

        return $this;
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressFormType;
use App\Repository\AddressRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AddressController extends AbstractController
{
    #[Route('/address/create', name: 'create_address')]
    public function create_address(Request $request,EntityManagerInterface $entityManager): Response
    {
        $address =  new Address();

        $form = $this->createForm(AddressFormType::class, $address);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->getUser()) {
                $address->setUser($this->getUser());
            }

            $entityManager->persist($address);
            $entityManager->flush();
            return $this->redirectToRoute('user_data');
        }

        return $this->render('address/add.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/address/edit/{id}', name: 'edit_address',  methods: ['GET','POST'])]
    public function edit_address (Request $request, AddressRepository $addressRepository, EntityManagerInterface $em, $id){
        $post = $addressRepository->find($id);

        //dd($post);
        $form = $this->createForm(AddressFormType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('user_data');
        }

        return $this->render('address/edit.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/address/delete/{id}', name: 'delete_address', methods: ['GET'])]
    public function delete_address(AddressRepository $addressRepository, Address $address): Response
    {
        $addressRepository->remove($address, true);

        return $this->redirectToRoute('user_data');
    }
}

templates/address/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add address!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ajouter une adresse</h1>

		{{ form(registrationForm) }}
</div>
{% endblock %}

templates/address/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit address!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Modifier une adresse</h1>

		{{ form(registrationForm) }}
</div>
{% endblock %}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add address!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ajouter une adresse</h1>

		{{ form(registrationForm) }}
</div>
{% endblock %}

templates/address/show.html.twig
<div>
	{% for address in app.user.address %}
		<h3>Adresse :</h3>
		<ul>
			<li>Street :
				{{ address.street }}</li>
			<li>City :
				{{ address.city }}</li>
			<li>Zip :
				{{ address.zip }}</li>
		</ul>

		<a href="{{path('edit_address',{'id':address.id})}}">
			<button>Modifier une adresse</button>
		</a>
		<a href="{{path('delete_address',{'id':address.id})}}">
			<button>Supprimer une adresse</button>
		</a>
	{% endfor %}

	<div>
		<a href="{{path('create_address')}}">
			<button>Ajouter une adresse</button>
		</a>
	</div>
</div>